### ISSUE TITLE
Icon和文本对齐方式的探索

### ISSUE THREAD

**Issue by goodmornight** [goodmornight/code-notes#1]
## 问题
在前端开发过程中，出现icon与文本无法居中问题。
![image](https://user-images.githubusercontent.com/17687454/114388152-e5ba8180-9bc5-11eb-973c-fca96fda574c.png)

### 方案一：`inline-flex`（成功解决问题）
```css
.btn-custom-style {
  display: inline-flex;
  align-items: center;
}
```
## 参考
[Icon和文本对齐方式的探索 | 掘金](https://juejin.cn/post/6844903693406437384)
[iconfont的字体为什么会偏下？| segmentfault](https://segmentfault.com/q/1010000007827433)
[小图标文字对齐的终极解决方案 | 博客园](https://www.cnblogs.com/zjx2011/p/5387638.html)
