### ISSUE TITLE
修改插件样式小tips

### ISSUE THREAD

**Issue by goodmornight** [goodmornight/code-notes#2]
## 问题
在修改vue-multiselect插件的样式时，发现没有提供样式修改接口，因此我只能选择暴力修改。通过Chrome浏览器查看页面html文件，使用vue-multiselect对应生成的div，通过覆盖样式来调整。
但通过全局样式覆盖明显是不明智的，因为可能你的组件适应该页面，但并不适合其他页面。
### 方案一：给组件添加id
通过id下的class样式覆盖。（但这个解决方案对于vue-multiselect无效）
### 方案二：给组件加一个空的class
通过这个空的class，把它的子class覆盖即可。
```vue
// vue
<multiselect
    class="host-select d-inline-block me-2"
    style="width:30%; min-height: 0;"
    v-model="selectedHost"
    :options="hosts"
    track-by="ip"
    label="ip"
    placeholder="选择主机"
    select-label="选择主机"
    selectedLabel="已选"
    deselectLabel="点击取消"
>
    <template slot="singleLabel" slot-scope="{ option }">{{ option.ip }}</template>
</multiselect>
```
```scss
.host-select .multiselect__tags {
    min-height: 0!important;
    padding: 0.25rem 0.5rem!important;
}
```
